### ISSUE TITLE
Error: write EPROTO 46176:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:c:\ws\deps\openssl\openssl\ssl\statem\statem_lib.c:1929:

### ISSUE THREAD

**Issue by Sathish787** [billylam/newman-reporter-testrail#10]
Test results are not posted to testrail and it throws error :
Error: write EPROTO 46176:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:c:\ws\deps\openssl\openssl\ssl\statem\statem_lib.c:1929:

// Create a title using project name if no better title is specified
      if (!title) {
		const path = (suiteId) ? `get_suite/${suiteId}` : `get_project/${projectId}`;
		console.log(`https://${domain}/index.php?/api/v2/${path}`);
		response = request('GET', `https://${domain}/index.php?/api/v2/${path}`, {
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Basic ${auth}`,
          },
        });
I did the same request from postman after turning off SSL verification and it worked. Could you share how to turn off SSL verification in your library

**Comment by billylam** [comment]
To clarify, is your issue that your testrail instance works over http instead of https, or is it that it works over https but you have an issue with your ssl certificate?

**Comment by Sathish787** [comment]
It works on https but having issue with ssl certificate. 

From Postman, i could fire request and get pass status code (200) after turning off SSL Certificate verification with username and password (not api key). So I was hoping some provision to turn off SSL certificate in the library

Please let me know if i miss information you need.

**Comment by billylam** [comment]
Ideally the testrail cert should be fixed but you can try disabling at the nodejs level with NODE_TLS_REJECT_UNAUTHORIZED=0 as an environment variable.

**Comment by Sathish787** [comment]
Thank you! Will try and let you know
