### ISSUE TITLE
[Question] add test result where custom field is required

### ISSUE THREAD

**Issue by TestaThaBesta** [billylam/newman-reporter-testrail#11]
Hi,

I am attempting to do the following: 

https://{url}.testrail.net/index.php?/api/v2/add_results_for_cases/{id} 

but

receive the below error due to custom fields being required on our testrail instance...

400:
{"error":"Field :custom_testenvironment is a required field."}

Any recommendations on how to handle this?

**Comment by billylam** [comment]
I've just published v1.0.15.

Try updating and adding
TESTRAIL_CUSTOM_custom_testenvironment=yourenvironment (or possibly TESTRAIL_CUSTOM_testenvironment depending on how testrail handles errors) to your run command

Let me know if there are any issues.
