### ISSUE TITLE
Incorrect value of Elapsed

### ISSUE THREAD

**Issue by liberstein** [billylam/newman-reporter-testrail#12]
Hi!
I use your report sometimes, but I get incorrect **Elapsed value**  = time Execution for a test. 
I'm using testrail-api and change Title, so I see Total duration of my current TestRun.

As you can see, in my case Total duration is 9.2 seconds.
http://i.imgur.com/DU7pcYq.png

But inside of each tests I have incorrect Elapsed time = 34s. That's very strange. This value I get from your reporter.
http://i.imgur.com/H0Hhmxr.png

I hope you can fix it. I expected, that value of Elapsed inside of test = tes Time execution.

**Comment by billylam** [comment]
I'm getting the elapsed time number directly from Newman, so I think there may be an issue with your localized version of TestRail.  To confirm, can you please try this and let me know what happens:

Make an add_result call with an existing test run case
http://docs.gurock.com/testrail-api2/reference-results#add_result

In the JSON body pass something like 
{
	"elapsed": "0.035s",
	"status_id": 5
}

Then please visit the case in testrail and let me know what the new elapsed time says.

**Comment by liberstein** [comment]
> I'm getting the elapsed time number directly from Newman, so I think there may be an issue with your localized version of TestRail. To confirm, can you please try this and let me know what happens:
> 
> Make an add_result call with an existing test run case
> http://docs.gurock.com/testrail-api2/reference-results#add_result
> 
> In the JSON body pass something like
> {
> "elapsed": "0.035s",
> "status_id": 5
> }
> 
> Then please visit the case in testrail and let me know what the new elapsed time says.
> 
> Also try
> 
> {
> "elapsed": "0,035s",
> "status_id": 5
> }

0.035 response:

`{
    "id": 175719,
    "test_id": 1795920,
    "status_id": 5,
    "created_by": 14,
    "created_on": 1586632238,
    "assignedto_id": null,
    "comment": null,
    "version": null,
    "elapsed": "35s",
    "defects": null
}`

and i see 35s O_o, works but incorrect, should be return 0,035

0,035 response:

{
    "error": "Field :elapsed is not in a valid time span format."
}

I think you're right and that's our internal problem

**Comment by liberstein** [comment]
if I send 
{
"elapsed": "0m 7s",
"status_id": 5
}

response

{
    "id": 175729,
    "test_id": 1795920,
    "status_id": 5,
    "created_by": 14,
    "created_on": 1586632904,
    "assignedto_id": null,
    "comment": null,
    "version": null,
    "elapsed": "7s",
    "defects": null
}

can you return in this format ? I mean round to an integer number of seconds, without dot

**Comment by billylam** [comment]
Did some reading and TestRail doesn't really support passing in ms so change was made.  Give 1.0.18 a try and let me know if you see any issues.
