### ISSUE TITLE
Newman test report customize display in Testrail

### ISSUE THREAD

**Issue by sourav044** [billylam/newman-reporter-testrail#14]
I am trying to display the test report that has been generated by the newman code.

Steps to reproduce the problem:

Install newman and Testrail.
Configure Testrail in the system.
Using API credentials from Testrail, Newman execute report and pass the generated report to testrail.
Command to execute it :

**newman run Scripts.postman_collection.json -e Auto.postman_environment.json --reporters cli,testrail**

Go to the particular project and test case of the Testrail and browse the report.

Expectation: I would like to show the report in a meaningful way rather than simply displaying it in a json format. This will allow the user to read it and find the easily issue that has been reported by the newman for the test cases.

The test report that is being generated by the newman and send to testrail as a content is not meaningful, check pic. Can anyone guide me how to achieve it ?

**Comment by billylam** [comment]
You didn't attach the pic.  Are you talking about the comment left at the end of tests that displays request / response in json?

**Comment by billylam** [comment]
1.0.20 now adds error message, if any, to the top of the TestRail comment.  I did NOT remove json request and response logging.  At a future time I may make a less verbose mode to not log them.

Reopen if this does not fix your issue.
