### ISSUE TITLE
Newman test report customize display in Testrail 

### ISSUE THREAD

**Issue by sourav044** [billylam/newman-reporter-testrail#15]
1. Newman Version 4.5.7
2. OS details Windows 10
3. Are you using Newman as a library? Yes, I am using it as a library.
4. Did you encounter this recently, or has this bug always been there: -> Recently
5. Expected behaviour: -> Newman test report customize display in Testrail
6. Command / script used to run Newman:
`newman run Scripts.postman_collection.json -e Auto.postman_environment.json --reporters cli,testrail`
7. Sample collection, and auxiliary files (minus the sensitive details):

Request: GET http://----/api/hello
Headers: [{"key":"User-Agent","value":"PostmanRuntime/7.21.0","system":true},{"key":"Accept","value":"*/*","system":true},{"key":"Cache-Control","value":"no-cache","system":true},{"key":"Postman-Token","value":"xxx","system":true},{"key":"Host","value":"10.1.4.157:11003","system":true},{"key":"Accept-Encoding","value":"gzip, deflate","system":true},{"key":"Connection","value":"keep-alive","system":true}]

Response: 200 OK
Headers: [{"key":"Content-Length","value":"2"},{"key":"Content-Type","value":"application/json; charset=utf-8"},{"key":"Server","value":"Microsoft-HTTPAPI/2.0"},{"key":"Date","value":"Sat, 25 Apr 2020 11:49:31 GMT"}]
Body: []

8.  Screenshots (if applicable):
[Image](https://user-images.githubusercontent.com/22783872/82198845-8652e380-991a-11ea-87cf-fe1b42ecf3e4.png)

Steps to reproduce the problem:

1. Install newman and Testrail.
2. Configure Testrail in the system.
3. Using API credentials from Testrail, Newman execute report and pass the generated report to testrail.

Command to execute it :
newman run Scripts.postman_collection.json -e Auto.postman_environment.json --reporters cli,testrail

Go to the particular project and test case of the Testrail and browse the report.
Expectation:
I would like to show the report in a meaningful way rather than simply displaying it in a json format.
This will allow the user to read it and find the easily issue that has been reported by the newman for the test cases.

**Comment by billylam** [comment]
Try version 1.0.21.

**Comment by sourav044** [comment]
Hopefully you are asking me to downgrade my Newman with version - 1.0.21.

**Comment by billylam** [comment]
No, 1.0.21 of this reporter.

**Comment by sourav044** [comment]
It worked but the body section still contains the JSON format data which is still not easy to understand. 

 
![image](https://user-images.githubusercontent.com/22783872/85282536-8a3dcc80-b4a9-11ea-9783-12b846ac71fa.png)

**Comment by billylam** [comment]
That will not be changed.  If JSON is returned it is more useful to more people to have raw json returned rather than any transformed JSON, so that a user can validate structure, run through a parser, etc.

If you truly need this functionality, feel free to fork the project and modify the code that adds comments for your own needs.  The line in question is https://github.com/billylam/newman-reporter-testrail/blob/master/lib/TestrailReporter.js#L77.
