### ISSUE TITLE
Parameter values are not shown in the result

### ISSUE THREAD

**Issue by junghanChoi** [billylam/newman-reporter-testrail#16]
reporter version: newman-reporter-testrail@1.0.22

Hello, I really enjoy to use testerail reporter.
My question is, do you have plan to add information about showing parameter values?
It seems that parameter values are not included on the result

`
C5837128 Status code is 400

Request: GET https://****.com/v1/alnet006/blocks   // there are more paramter values here. but not appeared. 
Headers:
User-Agent: PostmanRuntime/7.25.0
Accept: /
Cache-Control: no-cache
Postman-Token: 6879e4a3-c8c6-4c5f-a296-752a7aa92b73
Host: *****
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
`

**Comment by billylam** [comment]
Thank you for reporting this - it is a bug and should be fixed in 1.0.23.  Please reopen if you are having any issues with 1.0.23.
