### ISSUE TITLE
Data provided to TestRail exceeds the capacity limit

### ISSUE THREAD

**Issue by daterdots** [billylam/newman-reporter-testrail#18]
Hello! Thanks for this great tool. We're experiencing an issue when trying to send the results of fairly large and verbose tests to TestRail. It's unclear whether this happens when there are many test _cases_ trying to be sent at once, or if the response of one particular Postman test case has a _lot_ of content (e.g. test some route with `limit=10000`). Do you have any ideas for how to navigate this issue?
```
/usr/local/lib/node_modules/newman-reporter-testrail/node_modules/http-response-object/lib/index.js:51
            throw err;
            ^
Error: Server responded to https://mytestrail.testrail.io/index.php?/api/v2/add_results_for_cases/132 with status code 413:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>413 Request Entity Too Large</title>
</head><body>
<h1>Request Entity Too Large</h1>
The requested resource<br />/index.php<br />
does not allow request data with POST requests, or the amount of data provided in
the request exceeds the capacity limit.
</body></html>
```

**Comment by billylam** [comment]
I've published 1.0.24.  It should just trim the logging it does if you're getting a lot of data back from your calls.

Give that a shot and see if it fixes your use case; if not let me know and I'll see if I can think of another workaround.

**Comment by daterdots** [comment]
Thank you, @billylam, and FYI @hbenkhay

**Comment by hamzabenkhay** [comment]
Thank you @billylam for the fix , it worked for us 👌

**Comment by samueljwelsh** [comment]
Hi, I am still seeing the above issue, is there any other workarounds? Many thanks @billylam

**Comment by billylam** [comment]
@samueljwelsh The previous fix was to trim the logging, but it could still fail given enough calls with large amounts of data.

I've added a verbose option to disable request/response logging altogether.  Pull the latest version and try with the environmental variable VERBOSE=false

**Comment by bowens-zn** [comment]
I'm seeing this too, is there any way to even determine what the cap actually is, and how we might adjust our tests to be "smaller"?

**Comment by billylam** [comment]
@bowens-zn I don’t know exactly what the cap is but a [search of the testrail forums](https://discuss.gurock.com/t/add-results-for-cases-returns-error-413-request-entity-too-large/17658) shows it was recently lowered and is a few MB.  When logging nothing or only headers it should take a really high amount of tests (or lots of header data) to get there.


One thing to try - I deprecated the verbose option and instead changed it to TESTRAIL_LOGGING=none and forgot to update this thread (sorry).  Try that option and if you are still having issues, I will have to rewrite the code to update results in batches instead of all at once, which may take a while.

**Comment by daterdots** [comment]
@hbenkhay I think this might be what has been happening to us recently

> @bowens-zn I don’t know exactly what the cap is but a [search of the testrail forums](https://discuss.gurock.com/t/add-results-for-cases-returns-error-413-request-entity-too-large/17658) shows it was recently lowered and is a few MB. When logging nothing or only headers it should take a really high amount of tests (or lots of header data) to get there.
> 
> One thing to try - I deprecated the verbose option and instead changed it to TESTRAIL_LOGGING=none and forgot to update this thread (sorry). Try that option and if you are still having issues, I will have to rewrite the code to update results in batches instead of all at once, which may take a while.

**Comment by hbenkhay** [comment]
> @hbenkhay I think this might be what has been happening to us recently
> 

yes @daterdots , it definitely is. 

Thank you @billylam for the update !

**Comment by bowens-zn** [comment]
Still seeing this issue. TESTRAIL_LOGGING seems to have no effect.

**Comment by billylam** [comment]
Ok, that is really unfortunate because it may take a while to fix.  First I need to debug and check I'm not sending any extra data in the call accidentally.  If not, I need to figure out a way to chunk the results to allowed size and if I need to throttle the chunk sends as well.

**Comment by billylam** [comment]
@bowens-zn , can you let me know your approximate total number of tests being run at once?

**Comment by bowens-zn** [comment]
@billylam thanks for responding. ~200 tests.

**Comment by billylam** [comment]
Ok - please get the latest and try once again @bowens-zn .  I was sending error messages in comments with the "none" option which contributed to the data size limit.

**Comment by bowens-zn** [comment]
@billylam that seems to have worked! Thank you!!!!

**Comment by daterdots** [comment]
@bowens-zn and @billylam - for what it's worth, we wrote up this article on integrating Postman and Testrail on Fargate in case that's helpful for your future work https://www.geocene.com/backend/testing/infrastructure/2021/03/10/automating-api-testing-postman-fargate

**Comment by sakethalaxmi** [comment]
@billylam - I am still seeing this issue
I have updated my Newman version to 5.2.4 and still seeing this issue.
Any other workarounds?

Thankyou!

**Comment by billylam** [comment]
@sakethalaxmi Are you using TESTRAIL_LOGGING=none and on the latest version?

If you are and are still seeing issues, please try rerunning with only a few tests.  Once complete, click on the test case and see if you are only seeing `This test was marked as 'Passed/Failed'`.  If this is NOT the case, please open up a new issue for me to investigate the bug.

If you ARE only seeing this minimal logging, you might be running so many tests that it exceeds testrail's post size limit anyway.  Fixing this would require some thought and time, but you can either run your tests in subsets.  One way to do this is in the article linked above.

**Comment by sakethalaxmi** [comment]
Thank you for the quick reply @billylam  
I think for me the issue is a certain endpoint returns a lot of data in the response and somehow test rail is unable to  report a PASS/FAIL for that endpoint 
I tried removing the test from my collection and it worked, Will change the test data so that the endpoint returns less data

**Comment by daterdots** [comment]
@sakethalaxmi you might find our article on automation helpful: https://www.geocene.com/backend/testing/infrastructure/2021/03/10/automating-api-testing-postman-fargate
