### ISSUE TITLE
[Question] Plugin submit result per pm.test to testrail comment?

### ISSUE THREAD

**Issue by 4nif** [billylam/newman-reporter-testrail#21]
I just upgrade my plugin from `1.0.12` to `1.0.26`. I notice a really strange behaviour, I am not sure if this is a design changes or a bug

In previous version 1.0.12 if i have pm.test as below
```
const tc_id = "C123456"

pm.test(tc_id + " check abc", function() {
    pm.expect(responseData.abc).to.eql("Success")
});

pm.test(tc_id + " check id", function() {
    pm.expect(responseData.id).to.eql("123")
});
```

After test completed `newman-reporter-testrail` will submit as one result (one comment)

Now in version `1.0.26` postman `newman-reporter-testrail` submit pm.test as separate entity. In above case I saw two comment in testrail.
The problem is if i have 15 pm.test in one request, I see 15 comment in testrail for one testcases
Is it possible to toggle this on off if I prefer the old behavior like in version 1.0.12?

Thanks

**Comment by billylam** [comment]
Try 1.0.28 @4nif.  It won't compress everything into one comment, but it should make it so the logging is no longer duplicated.  Let me know if you see any issues.

**Comment by 4nif** [comment]
Looks better now, thanks @billylam 👍
