### ISSUE TITLE
newman: could not find "testrail" reporter

### ISSUE THREAD

**Issue by RSUIAutomation** [billylam/newman-reporter-testrail#26]
Newman is unable to find the reporter, despite them being installed next to each other. Only minor issue I see is the warn for har-validator, which newman's team seems to think is not an issue from their support threads I have read. 

```
rr@rr Documents % sudo npm i newman -g                              
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/newman -> /usr/local/lib/node_modules/newman/bin/newman.js
+ newman@5.2.2
updated 1 package in 5.111s
rr@rr Documents % sudo npm install newman-reporter-testrail --global
+ newman-reporter-testrail@1.0.30
updated 1 package in 2.409s
rr@rr Documents % npm list -g -depth=0                              
/usr/local/lib
├── newman@5.2.2
├── newman-reporter-testrail@1.0.30
└── npm@6.14.11

rr@rr Documents % newman run LikesServiceLocal.postman_collection.json -e /Users/rr/Documents/qa-likes-service.postman_environment.json  --reporters cli,testrail
newman: could not find "testrail" reporter
  ensure that the reporter is installed in the same directory as newman
  please install reporter using npm
```

Consistent issue, seems to be prevalent since March 2020 at least. No resolutions found. https://discuss.gurock.com/t/postman-and-testrail-integration/14354

**Comment by RSUIAutomation** [comment]
har-validator no longer supported - https://www.npmjs.com/package/har-validator

postman community doesn't think its a problem - https://github.com/postmanlabs/newman/issues/2602 and https://community.postman.com/t/windows-newman-installation-npm-warn-deprecated-har-validator/16972

**Comment by RSUIAutomation** [comment]
I have also tried installing newman-reporter-testrail into the newman npm_modules directly per a report about another reporter working after that change, but it did not resolve the issue with testrail reporter.

**Comment by billylam** [comment]
Try either installing newman and this reporter without sudo, or running your newman command with sudo and let me know what you see.

The linked issues do not look relevant to what you're seeing.  The deprecated package shouldn't matter and is a newman dependency anyway, not a dependency of this package.  The user in the linked bug report probably ran his command incorrectly, as he gets `could not find “” reporter` instead of `could not find “testrail” reporter`.

**Comment by RSUIAutomation** [comment]
Thanks for the prompt reply and good ideas. I am looking into how I can install them both without sudo for now, currently that errors out with permissions. Hopefully I can find the permissions soon and adjust them.

I did give a try at running newman with sudo, and saw similar results:

``` 
rr@rr Documents % sudo newman run LikesServiceLocal.postman_collection.json -e /Users/rr/Documents/qa-likes-service.postman_environment.json  --reporters 'cli,testrail'
Password:
newman: could not find "testrail" reporter
  ensure that the reporter is installed in the same directory as newman
  please install reporter using npm

newman

```

**Comment by RSUIAutomation** [comment]
I found I could do a non-sudo install if I installed locally, but seeing the same issue on run.

**Comment by billylam** [comment]
I'm pretty certain the issue is environmental.  cli reporter is included with newman, but if you install a different third party reporter and use it, do you see the same error?

One suggestion from googling, check your node version.  You should be on a [currently supported version](https://nodejs.org/en/about/releases/), even versions 10+.  You can use [http://nvm.sh](nvm) to switch between versions more easily.

**Comment by RSUIAutomation** [comment]
Thanks again for your thoughts I am also thinking the same way, it's something with this env I am on (new mac laptop /w some admin user profiles also on the machine). Trying to understand how I can ensure ownership over all the files chown -R me and the root files didnt fix for me yet.

Good idea to check other third parties, I also have it on my list to just switch my dev env and see if I can get it going.

Versions:
npm -v 
7.6.3
node -v
v14.16.0

I will update here with more results or resolutions when I have them.

**Comment by RSUIAutomation** [comment]
I was able to chown the modules files which resolved the issue with not being able to install node packages without sudo, but that was not able to resolve the overall issue.

I was able to install the newman-reporter-html and use it without issue.

Removing and readding testrail reporter did not work.

**Comment by billylam** [comment]
After looking more, I think I found a missed bug with the last merged pull request.  Can you retry installing the latest version of the package and giving it another shot?

**Comment by RSUIAutomation** [comment]
That worked! Thanks a lot!
