### ISSUE TITLE
Reporter is repeating multiple results in Testrail

### ISSUE THREAD

**Issue by RotonaK** [billylam/newman-reporter-testrail#28]
The reporter is creating multiple copies of the results in TestRail. It was repeating the same results over and over around 2-5 times in one test. The case ids were set on 3 tests on a single request. I am also running into the issue of "Entity Is Too Large" if my full test suite with VERBOSE=false, might be related?

**Comment by billylam** [comment]
If you set the same case id on different tests, they will all be recorded even if the request is the same.  This is by design to ensure any distinct test can fail the entire case.

For the second issue, are you seeing request and response logging with VERBOSE=false?  And how many test cases total does your suite have?

**Comment by RotonaK** [comment]
For the first issue. I expected only 3 results to be displayed on TestRail,
but it repeated those sets of tests multiple times. I got 2 pages worth,
and they were straight forward tests such as validating the response code.

The 2 second issue. I do see it once I set Newman with a folder with a
couple of tests. The response had the bearer token, headers, etc. It is
around 500 requests.

Thanks for the quick response.

**Comment by billylam** [comment]
I can't seem to reproduce this locally.  Can you provide the command you are using to run the tests, as well as an example of your tests and the testrail logging it produces?

**Comment by RotonaK** [comment]
'newman run test.json --folder "test" -e test_environment.json -r
cli,testrail'

I also have multiple requests in the pre-request and test in Postman. It
looks like it is also spitting out a request that did not have a case ID.

**Comment by billylam** [comment]
There may be an issue then with folders of collections then.  If you could let me know how many files in your test folder and general info about them (how many tests per collection?  Are the test cases duplicated in different files?  Anything else maybe relevant?) it might help track the bug down.

**Comment by billylam** [comment]
I've been able to reproduce the issue, logging is duplication when specifying folders.  Not sure when I'll be able to get a fix in for that, but I will also add an option to have zero logging, which should fix the other issue.

**Comment by billylam** [comment]
Update to the latest and run with TESTRAIL_LOGGING=none.  This should fix the second issue.  Reopen or open a new ticket if you have more information regarding the first, but it's not reproduceable for me.
