### ISSUE TITLE
getaddrinfo ENOTFOUND undefined undefined:443

### ISSUE THREAD

**Issue by lamngit1995** [billylam/newman-reporter-testrail#3]
Hi Guy !
I got a problems such as : 
\AppData\Roaming\npm\node_modules\newman-reporter-testrail\node_modules\syncrpc\lib\index.js:151
    throw error;
    ^

Error: getaddrinfo ENOTFOUND undefined undefined:443
Can you help me check it
Thanks

**Comment by billylam** [comment]
Did you set environment variables?  Try typing the following command on terminal and see if you see anything:

`env | grep -i testrail`

**Comment by lamngit1995** [comment]
I set environment variables follow the document of you in Re-request Script right?
Thanks

**Comment by billylam** [comment]
You need the environment variables here
https://github.com/billylam/newman-reporter-testrail#export-the-following-environment-variables

That error is most likely TESTRAIL_DOMAIN is not set.

**Comment by lamngit1995** [comment]
Thanks You

**Comment by aozdemir21** [comment]
remove the "www" beginning of TESTRAIL_DOMAIN variable.
You are supposed to pass TestRail domain. Do not pass a variable that includes protocol.

DO NOT include "TESTRAIL_DOMAIN=**www**.mypage.testrail.io" instead use "TESTRAIL_DOMAIN=mypage.testrail.io"
