### ISSUE TITLE
Need Custom Status IDs

### ISSUE THREAD

**Issue by jaymcmeans** [billylam/newman-reporter-testrail#32]
It would be really great to have the ability to supply custom status_id for Pass, Fail, and Skipped.  Simply having 3 new TESTRAIL_ optional environment variables:

TESTRAIL_PASS=1
TESTRAIL_FAIL=5
TESTRAIL_SKIPPED=4

Then if someone supplied any of thee variables it could use TESTRAIL_PASS=10 and supply 10 in the add_results_for_cases call.

It looks like the code would use a variable based on the Env variable instead of a hardcoded number in this code:

         if (assertion.skipped === true) {
            currentResult.status_id = **skipped_status_id**;
          } else {
            if (assertion.error) {
              currentResult.comment = currentResult.comment.concat(
                `\nError: ${JSON.stringify(assertion.error.message)}`,
              );
              currentResult.status_id = **failed_status_id**;
              if (
                this.results
                  .map((result) => result.case_id)
                  .includes(currentResult.case_id) &&
                !duplicateFailingCases.includes(currentResult.case_id)
              ) {
                duplicateFailingCases.push(currentResult.case_id);
              }
            } else currentResult.status_id = **passed_status_id**;

**Comment by jaymcmeans** [comment]
I am not a JavaScript person but I am guessing it is as simple as:

...
     
     this.logging = process.env.TESTRAIL_LOGGING || 'full';
      this.pass_id = process.env.TESTRAIL_PASSED_ID || 1;
      this.fail_id = process.env.TESTRAIL_FAILED_ID || 5;
      this.skipped_id = process.env.TESTRAIL_SKIPPED_ID || 4;
      this.customKeys = Object.keys(process.env).filter((key) =>
        key.startsWith('TESTRAIL_CUSTOM'),
      );
...

          if (assertion.skipped === true) {
            currentResult.status_id = this.skipped_id;
          } else {
            if (assertion.error) {
              currentResult.comment = currentResult.comment.concat(
                `\nError: ${JSON.stringify(assertion.error.message)}`,
              );
              currentResult.status_id = this.fail_id;
              if (
                this.results
                  .map((result) => result.case_id)
                  .includes(currentResult.case_id) &&
                !duplicateFailingCases.includes(currentResult.case_id)
              ) {
                duplicateFailingCases.push(currentResult.case_id);
              }
            } else currentResult.status_id = this.pass_id;

            if (this.logging.toLowerCase() === 'none')
              currentResult.comment = '';
...

    //
    // Behavior when duplicate results for one test case are found:
    // Keep all results to preserve test logging, but push
    //    a final failing result at the end if any failed to ensure failing status.
    duplicateFailingCases.forEach((testCase) => {
      this.results.push({
        case_id: testCase,
        status_id: this.fail_id,
      });
    });
  }

**Comment by billylam** [comment]
Thanks for the PR!  This was published to npm as 1.0.38.
