### ISSUE TITLE
Getting 400 add_results_for_cases -Testrail newman integration

### ISSUE THREAD

**Issue by reachTushar** [billylam/newman-reporter-testrail#35]
Hi billylam, need your help on below error.
**Command used** - newman run Testrail1.postman_collection.json -e "Staging.postman_environment.json" --reporters=cli,testrail

**Error returned** - Error: Server responded to https://financialservices.testrail.io/index.php?/api/v2/add_results_for_cases/1302 with status code 400:
[
{"error":"Field :custom_environment is a required field."}
    at Response.getBody (C:\Users\AppData\Roaming\npm\node_modules\newman-reporter-testrail\node_modules\http-response-object\lib\index.js:41:23)
    at TestRailReporter.pushToTestrail (C:\Users\AppData\Roaming\npm\node_modules\newman-reporter-testrail\lib\TestrailReporter.js:304:62)
    at TestRailReporter.onComplete (C:\Users\AppData\Roaming\npm\node_modules\newman-reporter-testrail\lib\TestrailReporter.js:47:12)
    at EventEmitter.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\newman-reporter-testrail\lib\TestrailReporter.js:10:12)
    at EventEmitter.emit (C:\Users\AppData\Roaming\npm\node_modules\newman\node_modules\eventemitter3\index.js:203:33)
    at done (C:\Users\\AppData\Roaming\npm\node_modules\newman\lib\run\index.js:297:29)
    at C:\Users\\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\backpack\index.js:58:34
    at PostmanCollectionRun._process (C:\Users\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\run.js:163:13)
    at PostmanCollectionRun.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\run.js:169:76)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  statusCode: 400,
]
Test names in collection are prefixed with test case id in test rail -
pm.test("C41924 Status code is 200.", function(){
    pm.response.to.have.status(200);
});

pm.test("C41924 Body has 'Token' field.", function(){
    pm.expect(jsonData.Token).to.exist;
});

**Comment by billylam** [comment]
Sorry, I saw this but forgot to reply.  For anyone having this type of problem, your admin has added custom required fields.  Use the [TESTRAIL_CUSTOM_*](https://github.com/billylam/newman-reporter-testrail#optional-environment-variables) environment variable to pass a value to it.

**Comment by reachTushar** [comment]
Thanks a lot billylam, that is very helpful. I told admin to disable the fields but now I can pass the value to the environment variable.

**Comment by reachTushar** [comment]
Hi billylam, Another issue I am facing is the request and response of api calls are not logged or saved in the comments section of the test rail. I want comments section in test rail to contain the request and response of the api calls. please let me know  how that can be achieved. At present only status of test case in test rail is set to passed and there is nothing saved in comments.

**Comment by billylam** [comment]
Strange, that is a feature enabled by default.  TESTRAIL_LOGGING=full on the command line manually enables it, if that doesn’t work there is an issue and I’ll have to check it out later.

**Comment by billylam** [comment]
Works for me.

![image](https://user-images.githubusercontent.com/3700437/126848759-da7c758c-4772-4446-9ea7-cb75bc9827a1.png)

**Comment by reachTushar** [comment]
> Strange, that is a feature enabled by default. TESTRAIL_LOGGING=full on the command line manually enables it, if that doesn’t work there is an issue and I’ll have to check it out later.

Thanks a lot for the response, actually didn't set TESTRAIL_LOGGING variable. now after assigning full to it I see request header and request url are logged in the comments section. But the request body and response body are not logged. can you pls suggest on this ?
![image](https://user-images.githubusercontent.com/70003241/126867195-9c94b149-593b-41ec-9180-54204813acd8.png)

**Comment by billylam** [comment]
Can you let me know if you happen to have an environment variable called `VERBOSE` set to false?
`env | grep -i verbose`
Also, what do you get when you try `npm list -g newman-reporter-testrail`

**Comment by reachTushar** [comment]
no I haven't set set VERBOSE variable. please let me know what is name of the variable, is it TESTRAIL_VERBOSE = true? I am running it on windows10.
the command returns -
![image](https://user-images.githubusercontent.com/70003241/126872098-c57a5206-eaef-4b9b-91c1-a28f41ba2188.png)

**Comment by billylam** [comment]
I may have a fix for the request issue, right now it only works when supplying a raw POST body value.

For the response issue, can you screenshot what you have as your response logging?  The return body should be under a key called "json"

![image](https://user-images.githubusercontent.com/3700437/126873967-fd8a8b4b-67d9-4ed2-9293-d7de8919ca3e.png)
