### ISSUE TITLE
Report status at the Test Step level

### ISSUE THREAD

**Issue by jaymcmeans** [billylam/newman-reporter-testrail#36]
An enhancement to set the status of a test at the step level would be much appreciated.  The API is fairly straight forward.  It is simply a matter of adding a "custom_step_result" for the case.  The curl command is:

curl --location --request POST 'https://testrail.company.com/index.php?/api/v2/update_case/12345 \
--header 'Content-Type: application/json' \
--data-raw '{
    "results": [
        {
            "case_id": 11112222,
            "status_id": 5,
            "comment": "Something 1",
            "custom_step_result": [
                {
                    "actual": "Actual Results for step 1",
                    "status_id": 1
                },
                {
                    "actual": "Actual Results for step 2",
                    "status_id": 5
                }
            ]
        },
        {
            "case_id": 11112223,
            "status_id": 5,
            "comment": "Something 2"
        }
    ]
}'

**Comment by billylam** [comment]
This may take a while to investigate.  We don't use step results in our instance and, as it turns out, our instance is also bugged when trying to use them.

**Comment by billylam** [comment]
Please try 1.0.40 and let me know if you see any glaring issues.  There are some limitations trying to map the data.  The assumptions that are made are that every test case has test steps, and that any steps that share the same case id definitely belong to the same parent case.
