### ISSUE TITLE
Use test case names instead of test case ids

### ISSUE THREAD

**Issue by mariosk** [billylam/newman-reporter-testrail#39]
First of all many thanks to the devel team for this great tool!!
Basically I'd like to ask you whether you could support usage of test case names instead of test case ids in postman collections. Let me explain why I need it and you may have another idea of how I could do it.

I use TestRail project as a singe repository with baseline support. When I use Master baseline test cases everything is fine with your tool. When I create a new baseline though inherited by Master the new Test Suite has new test case ids. This means that every time I want to run a Test Suite I have to change my postman collection's code test case ids, right?

That's why I'm asking for a new feature that could check against test case name instead of test case id. I think according to the TestRail API you have to find out what is the test case id by using the test case name or something like that.

**Comment by billylam** [comment]
While possible, there are some roadblocks:

* The recent change to bulk endpoints makes it more difficult to retrieve all test cases at once (pagination needed)
* TestRail API rate limit would require me to find and implement a rate limiting package
* I can foresee matching being finicky and need to research and make some decisions about dupe case names and inexact matches
* Lack of free time for me presently to code new features

I will try to take a look but unfortunately I would guess this won't be finished any time soon.

**Comment by billylam** [comment]
Please give 1.0.42 a try with TESTRAIL_TITLE_MATCHING=true and let me know if you see any issues.

**Comment by mariosk** [comment]
Yes @billylam it works like a charm ;-) Thanks!
