### ISSUE TITLE
Cannot set TESTRAIL_TITLE_MATCHING to `false`

### ISSUE THREAD

**Issue by vladimirzind** [billylam/newman-reporter-testrail#40]
Hi 
Thank you for creating this reporter.

I was wondering if there is a possibility to set TESTRAIL_TITLE_MATCHING to `false`?

It was introduced with issue https://github.com/billylam/newman-reporter-testrail/issues/39 , however it seems that it cannot be set to false.

In lib/environment.js:18 it was set to:
`env.useTitles = process.env.TESTRAIL_TITLE_MATCHING || 'false';`
which always evaluate to `true`.
 
My problem here is that when this environment variable is set to true the code in 
https://github.com/billylam/newman-reporter-testrail/blob/master/lib/TestrailReporter.js#L45 gets executed 
and calls 
https://github.com/billylam/newman-reporter-testrail/blob/master/lib/testRailApi.js#L34
which returns all test cases from the test suite and then breaks on:

  next = response._links.next;

since it returned some very wierd response with all 9k test cases
  
 I am most likely missing something, so please, feel free to correct me.

**Comment by billylam** [comment]
Thank you for bringing this up, as this can definitely be breaking for larger suites.

Unfortunately, I am without my computer for a few days, but will fix this as soon as I can.  In the meantime, feel free to use a previous version, or to edit https://github.com/billylam/newman-reporter-testrail/blob/master/lib/TestrailReporter.js#L45 in place (just changing the if statement to `this.env.useTitles.toLowerCase() === 'true'` should fix it)

**Comment by vladimirzind** [comment]
Thank you for your quick reply.

Pull request: https://github.com/billylam/newman-reporter-testrail/pull/41

**Comment by billylam** [comment]
Thank you for the PR.  Version 1.0.43 has been published, please let me know if you see further issues.

**Comment by vladimirzind** [comment]
Thank you for merge.
I can confirm that today I have not faced errors, and test runs have executed successfully.
