### ISSUE TITLE
Sugestion/Request | TESTRAIL_LOGGING option to log Test Case title from Postman

### ISSUE THREAD

**Issue by EOssesFrazoni** [billylam/newman-reporter-testrail#43]
Hi, this has been a very helpful and easy to use tool for our project.
One thing that would be a very nice addition is to have an option for TESTRAIL_LOGGING that allows to print the Test Name in Test Rail comments. 
![image](https://user-images.githubusercontent.com/83712411/151983954-49fb0782-5d61-442b-a38e-71c0f00dcf90.png)

For example: 
TESTRAIL_LOGGING = testname (new option)
Result:
Comment added to the test case in TestRail: "Name of the first test passed" or "Name of the second test failed".

Thanks!

**Comment by billylam** [comment]
Thanks!  After thinking about it I feel like it makes sense for title to always be in comments, even when that logging option is NONE.  Try newman-reporter-testrail@1.0.45 and set the TESTRAIL_LOGGING option to NONE and see if that is what you're looking for.

**Comment by EOssesFrazoni** [comment]
Hi @billylam, sorry for the delay on my answer. 
I'm using the latest npm package of this project (currently:  newman-reporter-testrail@1.0.46) but I don't see any comments being added to Test Cases using TESTRAIL_LOGGING = NONE, other than "This test case was marked as 'Passed'" default one.
Thanks!

**Comment by billylam** [comment]
Can you post the command you are using to run with personal info removed?

Are there multiple assertions mapped to one test case?  There is some deduplication where only the first case logs and subsequent cases give the generic message.

**Comment by EOssesFrazoni** [comment]
This is executed automatically from Azure DevOps Pipelines, and environment variables for TestRail are added separately in the UI, not in the command, but I've executed "SET TEST" command into the Agent and I get these (along with the private ones):
![image](https://user-images.githubusercontent.com/83712411/157947878-613cba9a-f4d7-482f-887b-44934c151596.png)

And here is the command I'm running:
`newman run https://api.getpostman.com/collections/***?apikey=*** --environment https://api.getpostman.com/environments/***?apikey=*** --reporters cli,junit,testrail --reporter-junit-export "C:\VSTSAgentsWork\Agent01\_work\5\s\Results\unitReport.xml"
`
Test case are only commented with the generic message:
![image](https://user-images.githubusercontent.com/83712411/157948293-61182853-c552-491b-86d9-5e6892553511.png)

**Comment by billylam** [comment]
Thanks - it appears this isn't set if using the "steps" option.  I personally don't use steps so it might take a little longer to fix, but should hopefully be there sometime next week.

**Comment by EOssesFrazoni** [comment]
I've disabled it afer merging all assertions into one test function and it works now! It was not srictly necessary so it is all good now. Many thanks for all your help and this for this project.
