### ISSUE TITLE
Test Run is being Closed after results are reported

### ISSUE THREAD

**Issue by EOssesFrazoni** [billylam/newman-reporter-testrail#49]
Hi!
In recent days, we've noticed that TestRuns are marked as Closed after Test Results are reported into it. 
This results in the following error in subsequent executions:
![image](https://user-images.githubusercontent.com/83712411/159527970-3c08c874-9f0c-4c17-afc9-50a29591cd6b.png)

It happens both when using TESTRAIL_CLOSE_RUN = false or without setting that variable. Started getting this error last Saturday, could it be TestRail API behavior changed from their side?

Thanks!

**Comment by billylam** [comment]
It’s likely a result of the latest deployment.  If possible use 1.0.46 for now and I’ll aim for a fix later today.
