### ISSUE TITLE
Is there any way we can create single testrail run which contains results from multiple collections?

### ISSUE THREAD

**Issue by mnataraj17** [billylam/newman-reporter-testrail#58]
I have 3 collections in postman which I am running all those separately on github actions with newman. I am able to run first collection and testrail run is getting created successfully. As a next step, I want to add results from 2nd and 3rd collection runs to the same run created initially.
Tried using TESTRAIL_RUNID with value "latest" but can see error as 
```
Error: Server responded to https://abc.testrail.io/index.php?/api/v2/add_results_for_cases/1567 with status code 400:
***"error":"Field :results contains one or more invalid results (case C42704 unknown or not part of the test run)"***
```
Looks like it's failing to add new cases/scenarios for existing test runs. 
I would appreciate any suggestions to resolve this problem. Thanks!

**Comment by billylam** [comment]
Does your suite contain test cases for all 3 collections?  As long as it does and you do not override TESTRAIL_INCLUDEALL I would think this would work.

**Comment by mnataraj17** [comment]
@billylam Thanks for responding!
It would be great if I can add only executed tests in the run. Is there any way to achieve this? Thanks!

**Comment by billylam** [comment]
I did some looking into in the TestRail developer API.  While it looks like it is possible, there is not a really simple way to do this, and I do not have a TestRail instance to test with currently to make sure changes are bug free.

If you would like to make a change yourself, I think it would involve a [get_tests](https://support.testrail.com/hc/en-us/articles/7077990441108#gettests) call to grab previous results, merging results (?) and passing into an [update_run](https://support.testrail.com/hc/en-us/articles/7077874763156-Runs#updaterun) call.  But again without a TestRail instance I can't make a change like this and would suggest using TESTRAIL_INCLUDEALL.
