### ISSUE TITLE
Testrail Api Key doesn't work

### ISSUE THREAD

**Issue by dobryakov** [billylam/newman-reporter-testrail#6]
Testrail Api Key doesn't work. Using password instead of key (e.g. TESTRAIL_APIKEY=your_password) works.

**Comment by billylam** [comment]
It seems to work for me.  Was it a newly generated key?  TestRail's API key generation is a little weird in that you have to first add the key then also save the page, or the key won't be added to your account.  If you don't save the page as well the key won't be saved even if it was generated.

Let me know if it is still an issue.

**Comment by billylam** [comment]
Reopen if still an issue
