### ISSUE TITLE
DOMAIN should be URL

### ISSUE THREAD

**Issue by nutjob4life** [billylam/newman-reporter-testrail#60]
My institution's Testrail installation is at

    https://my.institution.com/testrail/index.php

When the newman-reporter-testrail calls to add a run, it gets a 404.

The newman-reporter-testrail lets you specify `TESTRAIL_DOMAIN`, which is nice, but that makes a few assumptions:

- That your TestRail lives behind `https`, but it could be `http`
- That your TestRail lives at `/`, but it could have `any/sub/paths` before it

The `TESTRAIL_DOMAIN` ideally should be a `TESTRAIL_URL` so you can accommodate nonstandard or unusual installations.

**Comment by billylam** [comment]
I know this is semantically wrong, but for your use case does it work if you use

`TESTRAIL_DOMAIN="my.institution.com/testrail"` ?

I'd like to keep TESTRAIL_DOMAIN for backward compatibility purposes so maybe I can update the documentation instead, or have TESTRAIL_URL as a fallback.

**Comment by billylam** [comment]
For reference the domain variable is generally used [like this](https://github.com/billylam/newman-reporter-testrail/blob/master/lib/testRailApi.js#L94)
```
    const response = request(
      'GET',
      `https://${this.env.domain}/index.php?/api/v2/${path}`,
      { headers: this.headers },
    );
```

and I would think if you pass the rest of the path it would work.  http/https aside.

**Comment by nutjob4life** [comment]
@billylam you're brilliant.

YES! That is a great workaround. Thanks!

**Comment by billylam** [comment]
Great, thanks!  I'll just update the documentation then when I have the chance.
